// Code generated by protoc-gen-go. DO NOT EDIT.
// source: captcha.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 发送短信验证码请求体
type GenerateRequest struct {
	//@inject_tag: validate:"required" message:"required:接收者不能为空" json:"recipient"
	Recipient string `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient" validate:"required" message:"required:接收者不能为空"`
	//@inject_tag: validate:"required" message:"required:验证码类型" json:"type"
	Type                 int32    `protobuf:"varint,2,opt,name=type,proto3" json:"type" validate:"required" message:"required:验证码类型"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateRequest) Reset()         { *m = GenerateRequest{} }
func (m *GenerateRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateRequest) ProtoMessage()    {}
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_19591ef9dc6f2733, []int{0}
}

func (m *GenerateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateRequest.Unmarshal(m, b)
}
func (m *GenerateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateRequest.Marshal(b, m, deterministic)
}
func (m *GenerateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateRequest.Merge(m, src)
}
func (m *GenerateRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateRequest.Size(m)
}
func (m *GenerateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateRequest proto.InternalMessageInfo

func (m *GenerateRequest) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *GenerateRequest) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

// 发送短信验证码返回体
type GenerateResponse struct {
	//@inject_tag:  json:"id"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	//@inject_tag:  json:"expires"
	Expires              string   `protobuf:"bytes,2,opt,name=expires,proto3" json:"expires"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateResponse) Reset()         { *m = GenerateResponse{} }
func (m *GenerateResponse) String() string { return proto.CompactTextString(m) }
func (*GenerateResponse) ProtoMessage()    {}
func (*GenerateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_19591ef9dc6f2733, []int{1}
}

func (m *GenerateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateResponse.Unmarshal(m, b)
}
func (m *GenerateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateResponse.Marshal(b, m, deterministic)
}
func (m *GenerateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateResponse.Merge(m, src)
}
func (m *GenerateResponse) XXX_Size() int {
	return xxx_messageInfo_GenerateResponse.Size(m)
}
func (m *GenerateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateResponse proto.InternalMessageInfo

func (m *GenerateResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GenerateResponse) GetExpires() string {
	if m != nil {
		return m.Expires
	}
	return ""
}

// 验证请求信息
type VerifyRequest struct {
	//@inject_tag: validate:"required" message:"required:接收者不能为空" json:"recipient"
	Recipient string `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient" validate:"required" message:"required:接收者不能为空"`
	//@inject_tag: validate:"required" message:"required:验证码不能为空" json:"code"
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code" validate:"required" message:"required:验证码不能为空"`
	//@inject_tag: validate:"required" message:"required:验证码类型不能为空" json:"type"
	Type                 int32    `protobuf:"varint,3,opt,name=type,proto3" json:"type" validate:"required" message:"required:验证码类型不能为空"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyRequest) Reset()         { *m = VerifyRequest{} }
func (m *VerifyRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyRequest) ProtoMessage()    {}
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_19591ef9dc6f2733, []int{2}
}

func (m *VerifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyRequest.Unmarshal(m, b)
}
func (m *VerifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyRequest.Marshal(b, m, deterministic)
}
func (m *VerifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyRequest.Merge(m, src)
}
func (m *VerifyRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyRequest.Size(m)
}
func (m *VerifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyRequest proto.InternalMessageInfo

func (m *VerifyRequest) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *VerifyRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *VerifyRequest) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

// 验证返回信息
type VerifyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyResponse) Reset()         { *m = VerifyResponse{} }
func (m *VerifyResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyResponse) ProtoMessage()    {}
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_19591ef9dc6f2733, []int{3}
}

func (m *VerifyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyResponse.Unmarshal(m, b)
}
func (m *VerifyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyResponse.Marshal(b, m, deterministic)
}
func (m *VerifyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyResponse.Merge(m, src)
}
func (m *VerifyResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyResponse.Size(m)
}
func (m *VerifyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GenerateRequest)(nil), "captcha.GenerateRequest")
	proto.RegisterType((*GenerateResponse)(nil), "captcha.GenerateResponse")
	proto.RegisterType((*VerifyRequest)(nil), "captcha.VerifyRequest")
	proto.RegisterType((*VerifyResponse)(nil), "captcha.VerifyResponse")
}

func init() {
	proto.RegisterFile("captcha.proto", fileDescriptor_19591ef9dc6f2733)
}

var fileDescriptor_19591ef9dc6f2733 = []byte{
	// 233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x4e, 0x2c, 0x28,
	0x49, 0xce, 0x48, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x9c, 0xb9,
	0xf8, 0xdd, 0x53, 0xf3, 0x52, 0x8b, 0x12, 0x4b, 0x52, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b,
	0x84, 0x64, 0xb8, 0x38, 0x8b, 0x52, 0x93, 0x33, 0x0b, 0x32, 0x53, 0xf3, 0x4a, 0x24, 0x18, 0x15,
	0x18, 0x35, 0x38, 0x83, 0x10, 0x02, 0x42, 0x42, 0x5c, 0x2c, 0x25, 0x95, 0x05, 0xa9, 0x12, 0x4c,
	0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x60, 0xb6, 0x92, 0x0d, 0x97, 0x00, 0xc2, 0x90, 0xe2, 0x82, 0xfc,
	0xbc, 0xe2, 0x54, 0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x14, 0xa8, 0x76, 0xa6, 0xcc, 0x14, 0x21, 0x09,
	0x2e, 0xf6, 0xd4, 0x8a, 0x82, 0xcc, 0xa2, 0xd4, 0x62, 0xb0, 0x56, 0xce, 0x20, 0x18, 0x57, 0x29,
	0x94, 0x8b, 0x37, 0x2c, 0xb5, 0x28, 0x33, 0xad, 0x92, 0x68, 0x07, 0x24, 0xe7, 0xa7, 0xa4, 0x42,
	0x4d, 0x01, 0xb3, 0xe1, 0x8e, 0x62, 0x46, 0x72, 0x94, 0x00, 0x17, 0x1f, 0xcc, 0x58, 0x88, 0x93,
	0x8c, 0x5a, 0x19, 0xb9, 0xd8, 0x9d, 0x21, 0xfe, 0x16, 0xb2, 0xe7, 0xe2, 0x80, 0x39, 0x59, 0x48,
	0x42, 0x0f, 0x16, 0x38, 0x68, 0x41, 0x21, 0x25, 0x89, 0x45, 0x06, 0xea, 0x3f, 0x4b, 0x2e, 0x36,
	0x88, 0xf1, 0x42, 0x62, 0x70, 0x45, 0x28, 0xde, 0x90, 0x12, 0xc7, 0x10, 0x87, 0x68, 0x75, 0xe2,
	0x8c, 0x62, 0xd7, 0xb3, 0x06, 0xc7, 0x43, 0x12, 0x1b, 0x98, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x56, 0x8e, 0xf0, 0x1c, 0x9f, 0x01, 0x00, 0x00,
}
