database:
  engine: "mysql"
  host: "203.195.200.40"
  port: "3306"
  user: "captcha"
  password: "Liuqin76624291"
  name: "captcha"
  AutoMigrate: true
  maxOpenConns: 10
  maxIdleConns: 1
  connMaxLifetime: 60000000000
email:
  host: "smtp.163.com"
  port: 465
  username: "coolask@163.com"
  password: "QOQFLCKROCSJGMNR"
redis:
  host: "203.195.200.40:6379"
  password: "Liuqin76624291"
